const language = {
  EN: {
    connect: "for",
    Habitaciones: "Bedrooms",
    Estacionamientos: "Parking",
    Banos: "Bathrooms",
    Condicion: "Condition",
    Area: "Construction area",
    Ubicacion: "Location",
    Details: "Details",
    Description: "Description",
    Enlace: "LINK",
    mark: "BOOKMARK",
    speak: "Speak with an ",
    agente: "agent ",
    rest: "to learn more about this property.",
    member: "Member since",
    name: "Full Name",
    email: "Email",
    phone: "Phone number",
    contact: "Contact agent",
    copy: "Copied",
  },
  ES: {
    connect: "en",
    Habitaciones: "Habitaciones",
    Estacionamientos: "Estacionamientos",
    Banos: "Baños",
    Condicion: "Condicion",
    Area: "Area de construccion",
    Ubicacion: "Ubicacion",
    Details: "Details",
    Description: "Description",
    Enlace: "ENLACE",
    mark: "ME GUSTA",
    speak: "Habla con un ",
    agente: "agente ",
    rest: "para conocer más de esta propiedad.",
    member: "Miembro desde",
    name: "Nombre completo",
    email: "Correo electronico",
    phone: "Numero telefonico",
    contact: "Contactar agente",
    copy: "Copiado",
  },
};

export default language;
