const language = {
  EN: {
    ubicacionMapa: "Location map (e.g. address)",
    estado: "State",
    areaConstruccion: "Construction area in square meters",
    estacionamientos: "Parking spots",
    banos: "Bathrooms",
    habitaciones: "Bedrooms",
    precio: "Price",
    descripcion: "Description",
    detalles: "Details",
    municipio: "Municipality",
    departamento: "Department",
    datosPrincipales: "Main data",
    nuevaPropiedad: "New property",
    total: "Total",
    crear: "Create",
    cancelar: "Cancel",
    selecionar: "Select a municipality",
    donot: "Do not use commas or periods",
    usado: "Used",
    nuevo: "New",
  },
  ES: {
    ubicacionMapa: "Ubicación mapa (Ej. dirección)",
    estado: "Estado",
    areaConstruccion: "Área de construcción en metros cuadrados",
    estacionamientos: "Estacionamientos",
    banos: "Baños",
    habitaciones: "Habitaciones",
    precio: "Precio",
    descripcion: "Descripción",
    detalles: "Detalles",
    municipio: "Municipio",
    departamento: "Departamento",
    datosPrincipales: "Datos principales",
    nuevaPropiedad: "Nueva propiedad",
    total: "Total",
    crear: "Crear",
    cancelar: "Cancelar",
    selecione: "Seleciona un municipio",
    donot: "No utilizar commas o puntos",
    usado: "Usado",
    nuevo: "Nuevo",
  },
};

export default language;
