const language = {
  EN: {
    propiedades: "PropiedadesAhora ",
    message0: "is your best ally as a real estate advisor.",
    message1: "Have your own",
    message2: "digital catalog of your properties",
    message3: "and easily share it on any social network.",
    message4: "Take your professional brand to the next level with ",
    message5: "your own professional website",
    message6: "and promote your properties from there.",
    message7: "You will have a landing page ",
    message8: "automatically ",
    message9: "for each of your",
    message10: "properties.",
    message11: "Your properties will have a better ",
    message12: "presentation so you can share through your networks.",
    message13: "Rent out your properties ",
    message14: "by days, and you will be able to ",
    message15: "generate ",
    message16: "income easily.",
    message17: "Take the promotion of your",
    message18: "to the",
    message19: "next level.",
    message20: "Increase your sales",
    message21: " with the best and most modern tools for real estate agents.",
    message22: " START FOR FREE",
    message23: "COMING SOON",
  },
  ES: {
    propiedades: "PropiedadesAhora ",
    message0: "es tu mejor aliado como asesor inmobiliario",
    message1: "Cuenta con tu propio",
    message2: "catalogo digital de tus propiedades",
    message3: "y compártelo fácilmente por cualquier red social.",
    message4: "Lleva tu marca profesional al siguiente nivel con ",
    message5: "tu propio sitio web profesional",
    message6: "y promociona tus propiedades desde él.",
    message7: "Tendras un landing page ",
    message8: "automáticamente ",
    message9: "para cada una de tus",
    message10: "propiedades",
    message11: "Tus propiedades tendran una mejor ",
    message12: "presentacion, para que puedas compartir atraves de tus redes",
    message13: "Renta tus propiedades ",
    message14: "por dias, y podras ",
    message15: "generar ",
    message16: "ingresos con facilidad",
    message17: "Lleva la promoción de tus",
    message18: "al",
    message19: "siguiente nivel",
    message20: "Incrementa tus ventas",
    message21:
      " con las mejores y más modernas herramientas para inmobiliarios.",
    message22: " COMIENZA GRATIS",
    message23: "PROXIMAMENTE",
  },
  // Agrega más idiomas si es necesario
};

export default language;
